export enum EntityType {
  Project = "project",
  Repository = "repository",
  Module = "module",
  Service = "service",
  Feature = "feature",
  DomainConcept = "domain_concept",
  BusinessRule = "business_rule",
  Decision = "decision",
  Incident = "incident",
  Issue = "issue",
  PullRequest = "pull_request",
  Commit = "commit",
  CIJob = "ci_job",
  Deployment = "deployment",
  Workflow = "workflow",
  Skill = "skill",
  RiskArea = "risk_area",
  Person = "person",
  Team = "team",
}