import { ChangeRiskReport } from "../../core/inference/check-change-risk";

export const CHANGE_RISK_COMMENT_MARKER = "<!-- cognitive-os:pr-risk-comment -->";

const RISK_EMOJI: Record<ChangeRiskReport["overallRiskLevel"], string> = {
  low: "\u{1F7E2}",
  medium: "\u{1F7E1}",
  high: "\u{1F534}",
};

function moduleName(moduleId: string): string {
  return moduleId.replace(/^module\./, "");
}

function personName(personId: string): string {
  return personId.replace(/^person\./, "");
}

export function renderChangeRiskComment(report: ChangeRiskReport): string {
  const lines: string[] = [];

  lines.push(CHANGE_RISK_COMMENT_MARKER);
  lines.push(
    `### ${RISK_EMOJI[report.overallRiskLevel]} cognitive-os risk check — ${report.overallRiskLevel.toUpperCase()} risk`
  );
  lines.push("");
  lines.push(
    `${report.touchedModules.length} module(s) touched across ${report.files.length} changed file(s).`
  );
  lines.push("");

  if (report.modules.length === 0) {
    lines.push("_No tracked modules were touched by this change._");
    return lines.join("\n");
  }

  lines.push("| Module | Hotspot | Bus factor | Experts |");
  lines.push("|---|---|---|---|");

  for (const module of report.modules) {
    const hotspot = module.hotspot
      ? `${module.hotspot.riskLevel} (${module.hotspot.hotspotScore})`
      : "—";

    const busFactor = module.busFactor
      ? `${module.busFactor.riskLevel} (${module.busFactor.busFactor})`
      : "—";

    const experts = module.experts.length
      ? module.experts.map((e) => personName(e.personId)).join(", ")
      : "—";

    lines.push(`| ${moduleName(module.moduleId)} | ${hotspot} | ${busFactor} | ${experts} |`);
  }

  const invariantLines = report.modules.flatMap((module) =>
    module.relevantInvariants.map(
      (invariant) => `- **${moduleName(module.moduleId)}**: ${invariant.description}`
    )
  );

  if (invariantLines.length > 0) {
    lines.push("");
    lines.push("<details><summary>Architectural invariants touched</summary>");
    lines.push("");
    lines.push(...invariantLines);
    lines.push("");
    lines.push("</details>");
  }

  lines.push("");
  lines.push("_Generated by cognitive-os — run `npx cognitive-os check <files>` locally for details._");

  return lines.join("\n");
}
