import { ContextArtifact } from "./context-artifact";

export const CONTEXT_ARTIFACTS: ContextArtifact[] = [
  {
    id: "agents",
    type: "agent-context",
    title: "AGENTS.md",
    path: "outputs/agent-context/AGENTS.md",
    description: "General operating instructions for agents.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["agent", "context", "rules", "project", "architecture"],
  },
  {
    id: "agent-workflow",
    type: "agent-context",
    title: "WORKFLOW.md",
    path: "outputs/agent-context/WORKFLOW.md",
    description: "Standard workflow for agents preparing task context before making changes.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["workflow", "agent", "context", "task", "prepare"],
  },
  {
    id: "human-cognition",
    type: "skill",
    title: "Human Cognition Skill",
    path: "outputs/skills/human-cognition/SKILL.md",
    description: "Reasoning about ownership, expertise, review risk, collaboration, and bus factor.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["ownership", "expertise", "review", "collaboration", "bus factor", "contributor"],
  },
  {
    id: "skill-index",
    type: "skill",
    title: "Skill Index",
    path: "outputs/skills/INDEX.md",
    description: "Index of generated skills.",
    modules: ["outputs"],
    keywords: ["skill", "skills", "index", "context"],
  },
  {
    id: "architecture",
    type: "skill",
    title: "Architecture Skill",
    path: "outputs/skills/architecture/SKILL.md",
    description: "Architecture boundaries, layers, and invariants.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["architecture", "boundary", "layer", "dependency", "invariant"],
  },
  {
    id: "codebase-navigation",
    type: "skill",
    title: "Codebase Navigation Skill",
    path: "outputs/skills/codebase-navigation/SKILL.md",
    description: "Where files should live.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["file", "move", "module", "folder", "navigation", "placement"],
  },
  {
    id: "risk-hotspots",
    type: "skill",
    title: "Risk Hotspots Skill",
    path: "outputs/skills/risk-hotspots/SKILL.md",
    description: "Hotspot and risk context.",
    modules: ["core", "connectors", "knowledge", "outputs"],
    keywords: ["risk", "hotspot", "coupling", "refactor", "change"],
  },
  {
    id: "project-timeline",
    type: "skill",
    title: "Project Timeline Skill",
    path: "outputs/skills/project-timeline/SKILL.md",
    description: "Historical project evolution.",
    modules: ["core", "connectors", "knowledge", "outputs"],
    keywords: ["timeline", "history", "evolution", "scaffold", "bootstrap"],
  },
  {
    id: "onboarding",
    type: "skill",
    title: "Onboarding Skill",
    path: "outputs/skills/onboarding/SKILL.md",
    description: "Quick project orientation.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["onboarding", "overview", "start", "orientation"],
  },
  {
    id: "context-core",
    type: "context-pack",
    title: "Core Context Pack",
    path: "outputs/context-packs/core.md",
    description: "Context pack for core module work.",
    modules: ["core"],
    keywords: ["core", "inference", "timeline", "extraction", "orchestration"],
  },
  {
    id: "context-connectors",
    type: "context-pack",
    title: "Connectors Context Pack",
    path: "outputs/context-packs/connectors.md",
    description: "Context pack for connector work.",
    modules: ["connectors"],
    keywords: ["connector", "github", "gitlab", "jira", "api", "ingestion"],
  },
  {
    id: "context-knowledge",
    type: "context-pack",
    title: "Knowledge Context Pack",
    path: "outputs/context-packs/knowledge.md",
    description: "Context pack for knowledge layer work.",
    modules: ["knowledge"],
    keywords: ["knowledge", "schema", "ontology", "graph", "events", "evidence"],
  },
  {
    id: "context-outputs",
    type: "context-pack",
    title: "Outputs Context Pack",
    path: "outputs/context-packs/outputs.md",
    description: "Context pack for generated outputs.",
    modules: ["outputs"],
    keywords: ["output", "report", "skill", "markdown", "context", "renderer"],
  },
  {
    id: "report-module-activity",
    type: "report",
    title: "Module Activity Report",
    path: "outputs/reports/module-activity.md",
    description: "Weighted module activity and related modules.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["activity", "changes", "module", "coupling"],
  },
  {
    id: "report-hotspots",
    type: "report",
    title: "Hotspot Report",
    path: "outputs/reports/hotspots.md",
    description: "Hotspot scores and risk signals.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["hotspot", "risk", "score", "confidence"],
  },
  {
    id: "report-timeline",
    type: "report",
    title: "Timeline Report",
    path: "outputs/reports/timeline.md",
    description: "Temporal project activity.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["timeline", "history", "phase", "scaffold", "evolution"],
  },
  {
  id: "report-architectural-invariants",
  type: "report",
  title: "Architectural Invariants Report",
  path: "outputs/reports/architectural-invariants.md",
  description: "Inferred architectural invariants, boundaries, and forbidden dependencies.",
  modules: ["connectors", "core", "knowledge", "outputs"],
  keywords: ["architecture", "invariant", "boundary", "dependency", "forbidden", "generated"],
},
  {
    id: "report-expertise",
    type: "report",
    title: "Expertise Report",
    path: "outputs/reports/expertise.md",
    description: "Inferred expertise areas and strongest modules per contributor.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["expertise", "author", "contributor", "skill area", "strongest module"],
  },
  {
    id: "report-ownership-graph",
    type: "report",
    title: "Ownership Graph Report",
    path: "outputs/reports/ownership-graph.md",
    description: "Ownership relationships between people and modules.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["ownership", "owner", "graph", "module"],
  },
  {
    id: "report-bus-factor",
    type: "report",
    title: "Bus Factor Report",
    path: "outputs/reports/bus-factor.md",
    description: "Bus factor risk and ownership concentration per module.",
    modules: ["connectors", "core", "knowledge", "outputs"],
    keywords: ["bus factor", "ownership", "risk", "contributor", "single point of failure"],
  },
];